/*
Actividad Sumativa 3 - Semana 8
Asignatura: Modelamiento de Bases de Datos
Alumno: Matías López Villarroel
*/

-- 1. Creacion de tablas principales (sin claves foraneas)
CREATE TABLE PAIS (
    id_pais NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 9 INCREMENT BY 3),
    nombre VARCHAR2(50),
    CONSTRAINT pk_pais PRIMARY KEY (id_pais)
);

CREATE TABLE CIUDAD (
    id_ciudad NUMBER,
    nombre VARCHAR2(50),
    id_pais NUMBER,
    CONSTRAINT pk_ciudad PRIMARY KEY (id_ciudad),
    CONSTRAINT fk_ciudad_pais FOREIGN KEY (id_pais) REFERENCES PAIS(id_pais)
);

CREATE TABLE SUCURSAL (
    id_sucursal NUMBER,
    direccion VARCHAR2(100),
    telefono VARCHAR2(20),
    id_ciudad NUMBER,
    CONSTRAINT pk_sucursal PRIMARY KEY (id_sucursal),
    CONSTRAINT fk_sucursal_ciudad FOREIGN KEY (id_ciudad) REFERENCES CIUDAD(id_ciudad)
);

CREATE TABLE MECANICO (
    id_mecanico NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 400 INCREMENT BY 7),
    primer_nombre VARCHAR2(50),
    segundo_nombre VARCHAR2(50),
    ap_paterno VARCHAR2(50),
    sueldo NUMBER,
    monto_impuesto NUMBER,
    bono_jefatura NUMBER,
    id_supervisor NUMBER,
    CONSTRAINT pk_mecanico PRIMARY KEY (id_mecanico),
    CONSTRAINT fk_mecanico_supervisor FOREIGN KEY (id_supervisor) REFERENCES MECANICO(id_mecanico)
);

CREATE TABLE CLIENTE (
    id_cliente NUMBER,
    rut VARCHAR2(10),
    dv CHAR(1),
    primer_nombre VARCHAR2(50),
    ap_paterno VARCHAR2(50),
    email VARCHAR2(100),
    telefono VARCHAR2(20),
    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente)
);

CREATE TABLE AUTOMOVIL (
    patente VARCHAR2(10),
    marca VARCHAR2(50),
    modelo VARCHAR2(50),
    anio NUMBER,
    id_cliente NUMBER,
    CONSTRAINT pk_automovil PRIMARY KEY (patente),
    CONSTRAINT fk_auto_cliente FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id_cliente)
);

CREATE TABLE SERVICIO (
    id_servicio NUMBER,
    descripcion VARCHAR2(100),
    valor NUMBER,
    CONSTRAINT pk_servicio PRIMARY KEY (id_servicio)
);

-- Creacion de tabla mantencion con PK simple (se modificara despues en el caso 2)
CREATE TABLE MANTENCION (
    id_mantencion NUMBER,
    fecha DATE,
    estado VARCHAR2(20),
    costo_total NUMBER,
    id_sucursal NUMBER,
    id_mecanico NUMBER,
    patente VARCHAR2(10),
    CONSTRAINT pk_mantencion_inicial PRIMARY KEY (id_mantencion),
    CONSTRAINT fk_mant_sucursal FOREIGN KEY (id_sucursal) REFERENCES SUCURSAL(id_sucursal),
    CONSTRAINT fk_mant_mecanico FOREIGN KEY (id_mecanico) REFERENCES MECANICO(id_mecanico),
    CONSTRAINT fk_mant_auto FOREIGN KEY (patente) REFERENCES AUTOMOVIL(patente)
);

CREATE TABLE DETALLE_SERVICIO (
    id_mantencion NUMBER,
    id_servicio NUMBER,
    id_sucursal NUMBER, 
    CONSTRAINT pk_detalle PRIMARY KEY (id_mantencion, id_servicio),
    CONSTRAINT fk_detalle_mant_inicial FOREIGN KEY (id_mantencion) REFERENCES MANTENCION(id_mantencion),
    CONSTRAINT fk_detalle_serv FOREIGN KEY (id_servicio) REFERENCES SERVICIO(id_servicio)
);

-- 2. Creacion de secuencias solicitadas
CREATE SEQUENCE seq_servicio
START WITH 400
INCREMENT BY 2;

CREATE SEQUENCE seq_ciudad
START WITH 185
INCREMENT BY 5;


-- 3. Aplicando las restricciones y reglas de negocio del Caso 2
ALTER TABLE MANTENCION DROP COLUMN costo_total;

-- Ajuste de la PK de Mantencion para que sea compuesta
ALTER TABLE DETALLE_SERVICIO DROP CONSTRAINT fk_detalle_mant_inicial;
ALTER TABLE MANTENCION DROP PRIMARY KEY CASCADE;
ALTER TABLE MANTENCION ADD CONSTRAINT pk_mantencion_compuesta PRIMARY KEY (id_sucursal, id_mantencion);

ALTER TABLE DETALLE_SERVICIO 
ADD CONSTRAINT fk_detalle_mantencion FOREIGN KEY (id_sucursal, id_mantencion) 
REFERENCES MANTENCION(id_sucursal, id_mantencion);

-- Agregando validaciones a las tablas
ALTER TABLE CLIENTE ADD CONSTRAINT uk_cliente_email UNIQUE (email);

ALTER TABLE CLIENTE ADD CONSTRAINT chk_cliente_dv 
CHECK (dv IN ('0','1','2','3','4','5','6','7','8','9','K'));

ALTER TABLE MECANICO ADD CONSTRAINT chk_mecanico_sueldo 
CHECK (sueldo >= 510000);

ALTER TABLE MANTENCION ADD CONSTRAINT chk_mantencion_estado 
CHECK (estado IN ('Reserva', 'Ingresado', 'Entregado', 'Anulado'));


-- 4. Poblamiento de datos de prueba para generar los informes
INSERT INTO PAIS (nombre) VALUES ('Chile');
INSERT INTO PAIS (nombre) VALUES ('Peru');
INSERT INTO PAIS (nombre) VALUES ('Colombia');

INSERT INTO CIUDAD (id_ciudad, nombre, id_pais) VALUES (seq_ciudad.NEXTVAL, 'Santiago', 9);
INSERT INTO CIUDAD (id_ciudad, nombre, id_pais) VALUES (seq_ciudad.NEXTVAL, 'Lima', 12);
INSERT INTO CIUDAD (id_ciudad, nombre, id_pais) VALUES (seq_ciudad.NEXTVAL, 'Bogota', 15);

INSERT INTO SERVICIO (id_servicio, descripcion, valor) VALUES (seq_servicio.NEXTVAL, 'Cambio Aceite', 45000);
INSERT INTO SERVICIO (id_servicio, descripcion, valor) VALUES (seq_servicio.NEXTVAL, 'Revisión Frenos', 67000);

-- Ingresando mecanicos de la figura 2
INSERT INTO MECANICO (primer_nombre, segundo_nombre, ap_paterno, sueldo, monto_impuesto, bono_jefatura, id_supervisor) 
VALUES ('Pedro', 'Jose', 'Manriquez', 759000, 23980, NULL, NULL);

INSERT INTO MECANICO (primer_nombre, segundo_nombre, ap_paterno, sueldo, monto_impuesto, bono_jefatura, id_supervisor) 
VALUES ('Felipe', 'M.', 'Vidal', 759000, 25580, NULL, 400);

INSERT INTO MECANICO (primer_nombre, segundo_nombre, ap_paterno, sueldo, monto_impuesto, bono_jefatura, id_supervisor) 
VALUES ('Juan', 'Pablo', 'Sanchez', 859000, 25580, NULL, 400);


-- 5. Generacion de los Informes Finales (Caso 4)

-- Informe 1: Mecanicos sin bono y con impuesto bajo 40.000
SELECT 
    id_mecanico AS "ID MECANICO",
    primer_nombre || ' ' || ap_paterno AS "NOMBRE MECANICO",
    sueldo AS "SALARIO",
    monto_impuesto AS "IMPUESTO ACTUAL",
    (monto_impuesto * 0.8) AS "IMPUESTO REBAJADO", 
    sueldo - (monto_impuesto * 0.8) AS "SUELDO CON REBAJA IMPUESTOS"
FROM MECANICO
WHERE bono_jefatura IS NULL 
  AND monto_impuesto < 40000
ORDER BY "IMPUESTO ACTUAL" DESC, ap_paterno ASC;

-- Informe 2: Ajuste salarial del 5%
SELECT 
    id_mecanico AS "IDENTIFICADOR",
    primer_nombre || ' ' || segundo_nombre || ' ' || ap_paterno AS "MECANICO",
    sueldo AS "SALARIO ACTUAL",
    (sueldo * 0.05) AS "AJUSTE", 
    (sueldo * 1.05) AS "SUELDO REAJUSTADO"
FROM MECANICO
WHERE (sueldo BETWEEN 600000 AND 900000) 
   OR id_supervisor IS NULL
ORDER BY "SALARIO ACTUAL" ASC, "MECANICO" DESC;